# Generated by Django 5.2.7 on 2025-10-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.BigIntegerField(default=1000),
        ),
    ]
